### DISCUSSION TITLE
How to make this work well with Ubiquiti UniFi Protect cameras and Prusa Connect

### DISCUSSION THREAD

**Discussion by jakkuh** [jtee3d/prusa_connect_rtsp#8] [Show and tell]
UniFi Protect camera's output a bit of a weird RTSP stream that [Prusa Connect](https://connect.prusa3d.com/) doesn't like, and I didn't want to use a bunch of processing power to re-encode it, so instead, here's how you can use go2rtc to generate a single frame feed with next to no processing power, and then pipe it to [Prusa Connect](https://connect.prusa3d.com/) with jtee3d's lovely script. :)

### 1. Enable one of the RTSP links for the printer's camera in UniFi Protect
![image](https://github.com/user-attachments/assets/69cc2dd5-04b0-4a37-bfdc-91c3fb6cc866)

### 2. Edit the UniFi RTSP link
- Change "rtsps" to "rtsp"
- Change the port from "7441" to "7447"
- Remove "?enableSrtp" from the end of the link

BEFORE:
`rtsps://1.2.3.4:7441/RgFgRh2exLK7dpQi?enableSrtp`

AFTER:
`rtsp://1.2.3.4:7447/RgFgRh2exLK7dpQi`

### 3. Add the edited RTSP link to the go2rtc config with a text editor or the go2rtc WebUI (`http://<GO2RTC-IP>:1984`)
```
streams:
    3dprinter:
      - rtsp://1.2.3.4:7447/RgFgRh2exLK7dpQi
```

### 4. Copy the camera stream's single jpeg frame from go2rtc into the [prusa_connect_rtsp](https://github.com/jtee3d/prusa_connect_rtsp/) RSTP_URLS list along with the token from [Prusa Connect](https://connect.prusa3d.com/).
![image](https://github.com/user-attachments/assets/eb0f458b-43f0-4a2a-a455-6fb2b6b8400a)

```
services:
  prusa_connect_rtsp:
    image: jtee3d/prusa_connect_rtsp:latest
    restart: unless-stopped
    environment:
      RTSP_URLS: >
        http://<GO2RTC-IP>:1984/api/frame.jpeg?src=<GO2RTC CAMERA STREAM NAME> # <----- GO2RTC STREAM LINK HERE
      TOKENS: >
        uq3jWPaiOOjYRWCG # <----- PRUSA CONNECT CAMERA TOKEN HERE
```

### 5. Restart the compose stack and check that it's working in Prusa Connect! :D

-----

Full Docker Compose Example:
```
services:
  prusa_connect_rtsp:
    image: jtee3d/prusa_connect_rtsp:latest
    restart: unless-stopped
    environment:
      RTSP_URLS: >
        http://<GO2RTC IP>:1984/api/frame.jpeg?src=<GO2RTC CAMERA STREAM NAME> # <----- GO2RTC STREAM LINK HERE
      TOKENS: >
        uq3jWPaiOOjYRWCG # <----- PRUSA CONNECT CAMERA TOKEN HERE
  go2rtc:
    image: alexxit/go2rtc
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver  # timezone for logs
    volumes:
      - "go2rtc:/config"
volumes:
    go2rtc:
```
